spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/forextrading?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true